import FlexberryEmberDemoSuggestionTypeEController from '../flexberry-ember-demo-suggestion-type-e';

var FlexberryEmberDemoSuggestionTypeENewController = FlexberryEmberDemoSuggestionTypeEController;
export default FlexberryEmberDemoSuggestionTypeENewController;
