import FlexberryEmberDemoLocalizationEController from '../flexberry-ember-demo-localization-e';

var FlexberryEmberDemoLocalizationENewController = FlexberryEmberDemoLocalizationEController;
export default FlexberryEmberDemoLocalizationENewController;
