import FlexberryEmberDemoLocalizationEController from '../flexberry-ember-demo-localization';

var FlexberryEmberDemoLocalizationENewController = FlexberryEmberDemoLocalizationEController;
export default FlexberryEmberDemoLocalizationENewController;

