import FlexberryEmberDemoApplicationUserEController from '../flexberry-ember-demo-application-user';

var FlexberryEmberDemoApplicationUserENewController = FlexberryEmberDemoApplicationUserEController;
export default FlexberryEmberDemoApplicationUserENewController;

