import FlexberryEmberDemoApplicationUserEController from '../flexberry-ember-demo-application-user-e';

var FlexberryEmberDemoApplicationUserENewController = FlexberryEmberDemoApplicationUserEController;
export default FlexberryEmberDemoApplicationUserENewController;
