import FlexberryEmberDemoSuggestionTypeEController from '../flexberry-ember-demo-suggestion-type';

var FlexberryEmberDemoSuggestionTypeENewController = FlexberryEmberDemoSuggestionTypeEController;
export default FlexberryEmberDemoSuggestionTypeENewController;

